config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followes'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "search_book" => "books#search_book"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#followers", as: "followers"
    get "followes"  => "relationships#followes", as: "followes"
    get "search" => "users#search"
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    @book_comment = BookComment.new
    # redirect_to request.referer
  end

  def destroy
    BookComment.find(params[:id]).destroy
    # redirect_to request.referer
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
      <table>
        <% book.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= link_to user_path(book_comment.user.id) do %>
                <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
                <%= book_comment.user.name %>
              <% end %>
            </td>
            <td>
              <%= book_comment.comment %>
            </td>
            <% if book_comment.user == current_user %>
              <td>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn btn-danger" ,remote: true %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>

app/views/book_comments/_comments_counter.html.erb
<p>コメント数：<%= book.book_comments.count %></p>

app/views/book_comments/create.js.erb
$("#comments").html("<%= j (render 'book_comments/comments', book: @book ) %>");
$(".comments-counter").html("コメント数: <%= @book.book_comments.count %>");
$("#comment-form").val("");

app/views/book_comments/destroy.js.erb
$("#comments").html("<%= j (render 'book_comments/comments', book: @book ) %>");
$(".comments-counter").html("コメント数: <%= @book.book_comments.count %>");