config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followes'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "search_book" => "books#search_book"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#followers", as: "followers"
    get "followes"  => "relationships#followes", as: "followes"
    get "search" => "users#search"
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # has_many :tr_relationships ,class_name: "Relationship" , foreign_key: "follower_id", dependent: :destroy
  has_many :re_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :followes, through: :relationships, source: :followed
  has_many :followers, through: :re_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    profile_image.attached? ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followes?(user)
    followes.include?(user)
  end

  def self.looks(search, word)
    if word == ""
      @user = User.all
    elsif search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    else
      @user = User.where("name LIKE?", "%#{word}%")
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :ensure_correct_user, only: [:update]
  before_action :ensure_guest_user, only: [:edit]
  def show
    @user = User.find(params[:id])
    @books = @user.books.order("#{sort_column} #{sort_direction}").page(params[:page])
    @book = Book.new
    @followers = @user.followers.all
    @today_books = @user.books.created_days_ago(0)
    @yesterday_books = @user.books.created_days_ago(1)
    @thisweek_books = @user.books.where(created_at: [1.week.ago.midnight..Time.now])
    @lastweek_books = @user.books.where(created_at: [3.week.ago.midnight..1.week.ago.end_of_day])
  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE?', "#{create_at}%"]).count
    end
  end

  def index
    @users = User.page(params[:page])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def  ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followes.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><% unless user == current_user %>
              <% if current_user.followes?(user) %>
                <%= link_to "フォロー外す" , user_relationships_path(user.id) ,method: :delete %>
              <% else %>
                <%= link_to "フォローする" , user_relationships_path(user.id) ,method: :post %>
              <% end %>  
        <% end %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
    <tr>
      <%= paginate users %>
    </tr>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user_followes_path(user.id) do %>
      <%= user.followes.count %>
    <% end %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user_followers_path(user.id) do %>
      <%= user.followers.count %>
    <% end %></th>
  </tr>
</table>
<% if user.name != "guestuser" %>　
  <div class='row'>
    <% if user == current_user %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% elsif current_user.followes?(user) %>
      <%= link_to "フォロー外す" , user_relationships_path(user.id), method: :delete, class:"btn btn-primary" %>
    <% else %>
      <%= link_to "フォローする" , user_relationships_path(user.id), method: :post , class:"btn btn-success" %>
    <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= search_book %>
      </td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :profile_image, "Image" %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-md-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
            <%= render 'info', user: current_user %>
                
            <h2 class="mt-3">New book</h2>
            <%= render 'books/form', book: @book %>

        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
            <%= render 'index',users: @users %>
        </div>
    </div>
</div>

<!--<h2>User info</h2>-->
<!--<%#= render 'info', user: current_user %>-->

<!--<h2 class="mt-3">New book</h2>-->
<!--<%#= render 'books/form', book: @book %>-->

<!--<h2>Users</h2>-->
<!--<%#= render 'index',users: @users %>-->

app/views/users/search.js.erb
$("#search-result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user , followers: @followers %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <h4>投稿数の前日比・前週比</h4>
      <table class="table-bordered table">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_books.count %></td>
            <td><%= @yesterday_books.count %></td>
            <td>
              <% if @today_books.count == 0 || @yesterday_books.count == 0 %>
                <%= "0%" %>
              <% else %>
                <% ratio = @today_books.count / @yesterday_books.count.to_f %>
                <%= (ratio * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @thisweek_books.count %></td>
            <td><%= @lastweek_books.count %></td>
            <td>
              <% if @thisweek_books.count == 0 || @lastweek_books.count == 0 %>
                <%= "0%" %>
              <% else %>
                <% ratio = (@thisweek_books.count / @lastweek_books.count.to_f) * 100 %>
                <%= ratio.to_i %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <h4>7日分の投稿数</h4>
      <table class="table table-bordered">
        <thead>
          <tr>
            <% for i in (1..6) do %>
              <th><%= 7 - i.to_i %>日前</th>
            <% end %>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% for i in (1..7) do %>
              <td>
                <% d = 7 - i.to_i %>
                <%= @user.books.created_days_ago(d).count %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <h4 class="mt-5">投稿数検索</h4>
      <div class="form-group">
        <%= form_with url:user_search_path(@user),method: :get, local: false do |f| %>
          <%= f.date_field :created_at %>
          <%= f.submit'検索', class:"btn btn-danger" %>
        <% end %>
      </div>
      <div id="search-result">
        <% if @search_book.present? %>
          <%= render'search', search_book: @search_book %>
        <% end %>
      </div>
      <h4 class="mt-5">7日間の投稿数の遷移</h4>
      <%= line_chart [['6日前',@user.books.created_days_ago(6).count], ['5日前', @user.books.created_days_ago(5).count], ['4日前', @user.books.created_days_ago(4).count], ['3日前', @user.books.created_days_ago(3).count], ['2日前', @user.books.created_days_ago(2).count], ['1日前', @user.books.created_days_ago(1).count], ['今日', @user.books.created_days_ago(0).count]] %>
    </div>
  </div>
</div>