config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followes'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "search_book" => "books#search_book"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#followers", as: "followers"
    get "followes"  => "relationships#followes", as: "followes"
    get "search" => "users#search"
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  # validates :rate, numericality: {
  #   less_than_or_equal_to: 5,
  #   greater_than_or_equal: 0
  # }, presence: true
  
  scope :created_days_ago, ->(n) { where(created_at: n.days.ago.all_day) }


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.search(search_word)
    Book.where(['category LIKE?', "#{search_word}"])
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backeard_match"
      @book = Book.where("title LIKE?", "%#{word}")
    else
      @book = Book.where("title LIKE?", "%#{word}%")
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @books = Book.order("#{sort_column} #{sort_direction}").page(params[:page])
    @book = Book.new
  end
  
  def search_book
    @books = Book.search(params[:keyword]).page(params[:page])
    @range = "Book"
    @word = params[:keyword]
    
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :category, :rate)
  end
  

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category, "Tag" %>
    <%= f.text_field :category, class:"form-control" %>
  </div>
  <div class="form-group" id="star-rate">
    <%= f.label :rate, "評価", class:"col-md-3 col-form-label" %>
    <%= f.hidden_field :rate,id: :review_star %>
  </div>
  <% if book.id == nil %>
  <!--星評価-->
    <script>
      $('#star-rate').empty();
      $('#star-rate').raty({
        size: 36,
        starOff: '<%= asset_path('star-off.png') %>',
        starOn: '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'book[rate]',
        half: true,
      })
    </script>
  <% else %>
    <script>
      $('#star-rate').empty();
      $('#star-rate').raty({
        size: 36,
        starOff: '<%= asset_path('star-off.png') %>',
        starOn: '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'book[rate]',
        half: true,
        readOnly: true,
        score: <%= book.rate %>
        // 編集画面からは星を変更できない
      })
    </script>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <div>
    <%= sort_order "created_at", "新しい順" %> | <%= sort_order "rate", "評価の高い順" %>
  </div>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <%= link_to book.category, search_book_path(keyword: book.category) %>
        </td>
        <td id="favorite_buttuons<%= book.id %>">
        <%= render "favorites/favorite", book: book %>
        </td>
        <td>
          <p>コメント数：<%= book.book_comments.count %></p>
        </td>
        <td id="star-rate<%= book.id %>">
          <%= render 'books/rate', book: book %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate books %> 

app/views/books/_rate.html.erb
<script>
  $('#star-rate<%= book.id %>').empty();
  $('#star-rate<%= book.id %>').raty({
    size: 36,
    starOff: '<%= asset_path('star-off.png') %>',
    starOn: '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'book[rate]',
    half: true,
    readOnly: true,
    score: <%= book.rate %>
  })
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/search_book.html.erb
<%= render "layouts/searches", range: @range, word: @word, books: @books %>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= @book.category %></td>
          <td id="favorite_buttuons<%= @book.id %>">
            <%= render "favorites/favorite", book: @book %>
          </td>
          <td class="comments-counter">
            <%= render "book_comments/comments_counter", book: @book %>
          </td>
          <td>
            <div id="star-rate<%= @book.id %>"></div>
            <%= render'books/rate', book: @book %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <div id="comments">
        <%= render "book_comments/comments" , book: @book %>
      </div>
      <div class="form-group" >
        <%= form_with model: [@book, @book_comment], local: false do |f| %>
          <%= f.text_area :comment ,rows: "5" ,class:"form-control" ,  id:"comment-form"%>
          <%= f.submit "送信" ,class: "mt-1" %>
        <% end %>
      </div>
    </div>
  </div>
</div>