config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followes'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "search_book" => "books#search_book"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#followers", as: "followers"
    get "followes"  => "relationships#followes", as: "followes"
    get "search" => "users#search"
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> about
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([["User"],["Book"]]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect"],["前方一致","forward"],["後方一致","backward"],["部分一致","partial"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/layouts/_search_form.html.erb
<% if user_signed_in? %>
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([["User"],["Book"]]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect"],["前方一致","forward"],["後方一致","backward"],["部分一致","partial"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
    <%= form_with url: search_book_path, local: true, method: :get, class:"ml-3" do |tag| %>
      <%= tag.text_field :keyword %>
      <%= tag.submit "タグ検索", class:"btn btn-success" %>
    <% end %>
<% end %>

app/views/layouts/_searches.html.erb
<h2><%= "#{range} search for \"#{word}\"" %></h2>


<table class="table table-hovor table-inverse">
  <% if range == "User" %>
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  <% elsif range == "Book" %>
    <thead>
      <tr>
        <th>Image</th>
        <th>Title</th>
        <th>Opinion</th>
        <th>Tag</th>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image ,size: '50x50' %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>
            <%= link_to book.category, search_book_path(keyword: book.category) %>
          </td>
          <td id="favorite_buttuons<%= book.id %>">
            <%= render "favorites/favorite", book: book %>
          </td>
          <td>
            <p>コメント数：<%= book.book_comments.count %></p>
          </td>
          <td id="star-rate<%= book.id %>">
            <%= render 'books/rate', book: book %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%#= render 'layouts/search' ,class:"mx-auto" %>
      <main>
        <p id="notice"><%= notice %></p>
        <div class="d-flex justify-content-center mb-2">
          <%= render 'layouts/search_form'%>
        </div>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>